Django-Weather-master/qweather/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('weather.urls')),
]

Django-Weather-master/weather/urls.py
from django.conf.urls import url

from weather.views import HomeView, CityWeatherView, CitySearchListView

app_name = 'weather'
urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^search$', CitySearchListView.as_view(), name='search_results'),
    url(r'^(?P<city_id>\d+)$', CityWeatherView.as_view(), name='city_weather')
]

Django-Weather-master/weather/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Country(models.Model):
    code = models.CharField(max_length=2, primary_key=True)
    name = models.CharField(max_length=255)


class City(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    country = models.ForeignKey(Country,on_delete=models.CASCADE)

Django-Weather-master/weather/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.base import TemplateView

from weather.models import City
from weather.service import weather_by_city_id


class HomeView(TemplateView):
    template_name = 'weather/home.html'


class CitySearchListView(ListView):
    model = City
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        try:
            return super(CitySearchListView, self).get(request, *args, **kwargs)
        except Http404:
            response = redirect('weather:search_results')
            params = '?q={q};page={page}'.format(q=request.GET.get('q'), page=1)
            response['Location'] += params
            return response

    def get_queryset(self):
        city_name = self.request.GET.get('q')
        return self.model.objects.filter(name__istartswith=city_name)\
                                 .extra(select={'length': 'length(name)'})\
                                 .order_by('length', 'country_id')

    def get_context_data(self, **kwargs):
        context = super(CitySearchListView, self).get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')


        return context




class CityWeatherView(TemplateView):
    template_name = 'weather/city_weather.html'
    partial_template_name = 'weather/city_weather_partial.html'

    def get(self, request, *args, **kwargs):
        if request.is_ajax():

            return render(request, self.partial_template_name, self.get_context_data(**kwargs))
        return super(CityWeatherView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CityWeatherView, self).get_context_data(**kwargs)
        context['city_weather'] = weather_by_city_id(self.kwargs['city_id'])
        context['city_id'] = self.kwargs['city_id']
        return context

Django-Weather-master/weather/templates/weather/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>QWeather - {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'weather/images/favicon.png' %}"/>
    <link rel="stylesheet" href="{% static 'weather/css/vendor/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'weather/css/base.css' %}" />
    {% block styles %}{% endblock %}
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
                <header>
                    <a href="{% url 'weather:home' %}">
                        <img id="logo-header"
                             class="img-responsive"
                             src="{% static 'weather/images/logo.png' %}"
                             onmouseover="this.src='{% static 'weather/images/logo-glow.png' %}'"
                             onmouseout="this.src='{% static 'weather/images/logo.png' %}'">
                    </a>
                    {% include 'weather/searchform.html' %}
                </header>
                <main id="content">
                    {% block content %}{% endblock %}
                </main>
            </div>
        </div>
    </div>


</body>
</html>

Django-Weather-master/weather/templates/weather/city_list.html
{% extends 'weather/base.html' %}

{% load static %}

{% block title %}Search Results{% endblock %}

{% block styles %}<link rel="stylesheet" href="{% static 'weather/css/city_list.css' %}" />{% endblock %}

{% block content %}
    {% for city in city_list %}
        <p><a class="city-block" href="{% url 'weather:city_weather' city.id %}">
            {{ city.name }} ({{ city.country.name }})
        </a></p>
    {% empty %}
        <p>No cities found</p>
    {% endfor %}

  
{% endblock %}

Django-Weather-master/weather/templates/weather/city_weather.html
{% extends 'weather/base.html' %}
{% load static %}

{% block title %}{{ city_weather.city_name }}{% endblock %}

{% block styles %}<link rel="stylesheet" href="{% static 'weather/css/city_weather.css' %}" />{% endblock %}

{% block content %}
    <div id="weather">
        {% if city_weather.error %}
            <h2>Cannot get weather (HTTP Error)</h2>
        {% else %}
            {% include 'weather/city_weather_partial.html' %}
        {% endif %}
    </div>

{% endblock %}

Django-Weather-master/weather/templates/weather/city_weather_partial.html
<h2>{{ city_weather.city_name }} ({{ city_weather.country_name }})</h2>
<div class="media">

    <div id="weather-info" class="media-right">
        <p id="temperature">{{ city_weather.temperature }} °C</p>
        <p id="weather-title">{{ city_weather.weather }}</p>
        <p class="weather-descr">{{ city_weather.weather_description }}</p>
        <p class="weather-descr">humidity: {{ city_weather.humidity }}%</p>
        <p class="weather-descr">pressure: {{ city_weather.pressure }} hPa</p>
        <p class="weather-descr">wind: {{ city_weather.wind_speed }} m/s</p>
    </div>
</div>

Django-Weather-master/weather/templates/weather/home.html
{% extends 'weather/base.html' %}

{% load static %}

{% block title %}Main Page{% endblock %}

{% block styles %}<link rel="stylesheet" href="{% static 'weather/css/home.css' %}" />{% endblock %}

{% block content %}
    
{% endblock %}

Django-Weather-master/weather/templates/weather/searchform.html
<form id="searchform" action="{% url 'weather:search_results' %}" method="get">
    <div class="input-group">
        <input id="searchbox" class="form-control" name="q" type="text"
               placeholder="Search cities" required>
        <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
            </button>
        </div>
    </div>
</form>